package com.company.logicstic.modules.load.dto;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

public record LoadView(
        UUID id,
        Long number,
        String name,
        String type,
        String status,
        Double distance,
        Boolean isInProximity,
        OffsetDateTime dispatchedAt,
        OffsetDateTime pickedUpAt,
        OffsetDateTime deliveredAt,
        OffsetDateTime cancelledAt,
        UUID customerId,
        String customerName,
        UUID assignedTruckId,
        String assignedTruckNumber,
        UUID assignedDispatcherId,
        String assignedDispatcherName,
        String source,
        OffsetDateTime requestedPickupDate,
        OffsetDateTime requestedDeliveryDate,
        String notes,
        Boolean isHazmat,
        String hazmatClass,
        String unNumber,
        BigDecimal deliveryCostAmount,
        String deliveryCostCurrency,
        String originAddressLine1,
        String originAddressLine2,
        String originAddressCity,
        String originAddressState,
        String originAddressZipCode,
        String originAddressCountry,
        Double originLocationLatitude,
        Double originLocationLongitude,
        String destinationAddressLine1,
        String destinationAddressLine2,
        String destinationAddressCity,
        String destinationAddressState,
        String destinationAddressZipCode,
        String destinationAddressCountry,
        Double destinationLocationLatitude,
        Double destinationLocationLongitude
) {
}
